//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetType
    {
        public int AssetTypeId { get; set; }
        public string Name { get; set; }
        public int AvailableNumber { get; set; }
    }
}
